name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        publishToNuget:
          description: 'Publish to nuget'
          required: true
          default: true
          type: boolean

jobs:
  dotnet:
    uses: mathieumack/MyGithubActions/.github/workflows/dotnetlib.yml@main
    with:
      publishToNuget: false
      runOnImageName: 'windows'
      dotnetVersions: |
        4.5.x
        4.7.x
        4.8.x
    secrets:
      NUGETPACKAGEIDENTIFIER: ${{ secrets.NUGETPACKAGEIDENTIFIER }}
      SONAR_ORGANIZATION_CODE: ${{ secrets.SONAR_ORGANIZATION_CODE }}
      SONAR_PROJECT_CODE: ${{ secrets.SONAR_PROJECT_CODE }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}